"""Server-side PDF report generator for SCFCA.

FR-24: Audit reporting — system-wide activity report.
FR-25: Case reporting — per-case report with assets, tickets, documents.
FR-26: Reports are informational snapshots only.
NFR-10: Structured reports suitable for institutional and judicial use.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Sequence

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle("SCFCATitle", parent=_STYLES["Heading1"], fontSize=16, spaceAfter=12)
_SUBTITLE_STYLE = ParagraphStyle("SCFCASub", parent=_STYLES["Heading2"], fontSize=12, spaceAfter=8)
_BODY_STYLE = _STYLES["BodyText"]
_DISCLAIMER_STYLE = ParagraphStyle("Disclaimer", parent=_STYLES["Italic"], fontSize=8, textColor=colors.grey)

_TABLE_STYLE = TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2332")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, 0), 8),
    ("FONTSIZE", (0, 1), (-1, -1), 7),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4f8")]),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ("TOPPADDING", (0, 0), (-1, -1), 3),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
])


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def generate_audit_report(
    events: Sequence[Any],
    chain_status: dict,
    from_date: str | None = None,
    to_date: str | None = None,
) -> bytes:
    """Generate an audit report PDF. FR-24."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=1.5 * cm, rightMargin=1.5 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm)
    elements = []

    elements.append(Paragraph("SCFCA — Audit Report", _TITLE_STYLE))
    period = ""
    if from_date:
        period += f"From: {from_date}  "
    if to_date:
        period += f"To: {to_date}"
    elements.append(Paragraph(f"Generated: {_now_iso()}  {period}", _BODY_STYLE))
    elements.append(Spacer(1, 12))

    # Events table
    headers = ["Event ID", "Timestamp", "Actor", "Type", "Action", "Entity"]
    rows = [headers]
    for e in events:
        ts = e.timestamp if isinstance(e.timestamp, str) else (e.timestamp.isoformat(timespec="seconds") if e.timestamp else "")
        rows.append([
            e.id,
            ts,
            e.actor_id[:12] + "..." if len(e.actor_id) > 12 else e.actor_id,
            e.event_type,
            e.action,
            f"{e.entity_type or ''}:{e.entity_id or ''}",
        ])

    if len(rows) > 1:
        col_widths = [55, 90, 70, 55, 90, 80]
        t = Table(rows, colWidths=col_widths, repeatRows=1)
        t.setStyle(_TABLE_STYLE)
        elements.append(t)
    else:
        elements.append(Paragraph("No audit events found for the specified period.", _BODY_STYLE))

    elements.append(Spacer(1, 12))
    chain_ok = "VALID" if chain_status.get("ok") else "INVALID"
    elements.append(Paragraph(f"Hash chain integrity: {chain_ok} ({chain_status.get('count', 0)} events)", _BODY_STYLE))
    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "This report is an informational snapshot generated by the SCFCA system. "
        "It does not constitute authorization for any custody action. (FR-26)",
        _DISCLAIMER_STYLE,
    ))

    doc.build(elements)
    return buf.getvalue()


def generate_case_report(
    case: Any,
    assets: Sequence[Any],
    tickets: Sequence[Any],
    documents: Sequence[Any],
    handler_name: str,
) -> bytes:
    """Generate a per-case report PDF. FR-25."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=1.5 * cm, rightMargin=1.5 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm)
    elements = []

    elements.append(Paragraph(f"SCFCA — Case Report: {case.id}", _TITLE_STYLE))
    elements.append(Paragraph(f"Generated: {_now_iso()}", _BODY_STYLE))
    elements.append(Spacer(1, 12))

    # Case details
    elements.append(Paragraph("Case Details", _SUBTITLE_STYLE))
    detail_rows = [
        ["Field", "Value"],
        ["Case ID", case.id],
        ["Title", case.title],
        ["Wallet Ref", case.wallet_ref],
        ["Handler", handler_name],
        ["Status", case.custody_status],
    ]
    t = Table(detail_rows, colWidths=[120, 340])
    t.setStyle(_TABLE_STYLE)
    elements.append(t)
    elements.append(Spacer(1, 12))

    # Assets
    elements.append(Paragraph("Seized Assets", _SUBTITLE_STYLE))
    if assets:
        asset_rows = [["Asset ID", "Symbol", "Type", "Quantity", "Status"]]
        for a in assets:
            qty = float(a.quantity) if a.quantity else 0
            asset_rows.append([a.id, a.symbol, a.asset_type, f"{qty:.8f}", a.status])
        t = Table(asset_rows, colWidths=[60, 50, 60, 100, 80], repeatRows=1)
        t.setStyle(_TABLE_STYLE)
        elements.append(t)
    else:
        elements.append(Paragraph("No assets registered for this case.", _BODY_STYLE))
    elements.append(Spacer(1, 12))

    # Tickets
    elements.append(Paragraph("Ticket History", _SUBTITLE_STYLE))
    if tickets:
        ticket_rows = [["Ticket ID", "Type", "Status", "Created At"]]
        for tk in tickets:
            created = tk.created_at.isoformat(timespec="seconds") if hasattr(tk.created_at, "isoformat") else str(tk.created_at)
            display_status = tk.display_status if hasattr(tk, "display_status") else tk.status
            ticket_rows.append([tk.id, tk.ticket_type, display_status, created])
        t = Table(ticket_rows, colWidths=[60, 100, 100, 130], repeatRows=1)
        t.setStyle(_TABLE_STYLE)
        elements.append(t)
    else:
        elements.append(Paragraph("No tickets for this case.", _BODY_STYLE))
    elements.append(Spacer(1, 12))

    # Documents
    elements.append(Paragraph("Documents", _SUBTITLE_STYLE))
    if documents:
        doc_rows = [["Doc ID", "Filename", "SHA-256", "Upload Date"]]
        for d in documents:
            created = d.created_at.date().isoformat() if hasattr(d.created_at, "date") else str(d.created_at)
            doc_rows.append([d.id, d.filename, d.sha256_hex[:16] + "...", created])
        t = Table(doc_rows, colWidths=[60, 140, 110, 80], repeatRows=1)
        t.setStyle(_TABLE_STYLE)
        elements.append(t)
    else:
        elements.append(Paragraph("No documents for this case.", _BODY_STYLE))
    elements.append(Spacer(1, 24))

    elements.append(Paragraph(
        "This report is an informational snapshot generated by the SCFCA system. "
        "It does not constitute authorization for any custody action. (FR-26)",
        _DISCLAIMER_STYLE,
    ))

    doc.build(elements)
    return buf.getvalue()
